apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: storage-automation
spec:
  name: storage-automation
  organization: Default
  connection_secret: aap-access
  description: "Storage Automation SA"
  type: "OpenShift or Kubernetes API Bearer Token"
  kubernetes_api: https://api.open-svc-sts.k1wl.p1.openshiftapps.com:6443 
  kubernetes_bearer_token_secret: storage-automation
