---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-automation
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-automation
  annotations:
    kubernetes.io/service-account.name: storage-automation
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volume-manager 
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots", "volumesnapshotcontents", "volumesnapshotclasses"]
  verbs: ["patch", "get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volume-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volume-manager
subjects:
- kind: ServiceAccount
  name: storage-automation
  namespace: summit-aap
